version: "3.8"

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    env_file: .env

  graphql-api:
    build: .
    container_name: graphql-api
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      MONGO_URI: ${MONGO_URI}
    env_file: .env

