services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    env_file:
      - .env

  graphql-api:
    build:
      context: .
    container_name: graphql-api
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    env_file:
      - .env

volumes:
  mongo_data:
