// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewNote struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	URL         string `json:"url"`
	Date        string `json:"date"`
}

type NewProject struct {
	Title       string   `json:"title"`
	Description string   `json:"description"`
	Status      string   `json:"status"`
	Link        bool     `json:"link"`
	URL         string   `json:"url"`
	Giturl      *string  `json:"giturl,omitempty"`
	Tags        []string `json:"tags"`
}

type Note struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	URL         string `json:"url"`
	Date        string `json:"date"`
}

type Project struct {
	ID          string   `json:"id"`
	Title       string   `json:"title"`
	Description string   `json:"description"`
	Status      string   `json:"status"`
	Link        bool     `json:"link"`
	URL         string   `json:"url"`
	Giturl      *string  `json:"giturl,omitempty"`
	Tags        []string `json:"tags"`
}

type Query struct {
}
